version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports: 
      - ${MONGODB_PORT}:27017
    environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}